# Generated by Django 4.0.5 on 2022-07-09 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='duration',
        ),
    ]
