# Generated by Django 4.0.5 on 2022-07-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0002_remove_music_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
