# Generated by Django 4.0.5 on 2022-06-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0003_remove_music_audio_file_alter_music_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.CharField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIS9NmMDZNSiXrq6Q1C62ihL3MuLsXLfUw2w&usqp=CAU', max_length=600, null=True),
        ),
    ]
