# Generated by Django 4.0.5 on 2022-07-09 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_api', '0003_alter_music_artist_alter_music_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='added_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
