# Generated by Django 4.0.5 on 2022-06-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0005_alter_music_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
