# Generated by Django 4.0.8 on 2023-01-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0006_alter_music_audio_alter_music_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='plays',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
