# Generated by Django 4.0.5 on 2022-06-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0006_music_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='audio_link',
        ),
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(default='', upload_to='media/'),
        ),
    ]
