# Generated by Django 4.0.8 on 2023-01-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0007_music_plays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='plays',
            field=models.IntegerField(default=0),
        ),
    ]
